---
title: "Clustering_Total"
author: "Sophia Leeman"
date: "2023-04-06"
output: html_document
---

Perform Hierarchical Clustering on the dataset cleaned in PCA_Total.rmd
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
df_f <- read.csv("TrainTestDatasets/Train_CaseFatality_PCA.csv")
df_i <- read.csv("TrainTestDatasets/Train_Incident_PCA.csv")

head(df_f)
```

```{r}
#numeric_cols_f <- sapply(df_f, is.numeric)
df_f$State <- as.factor(df_f$State)
df_f$Month <- as.factor(df_f$Month)
clusters <- hclust(dist(subset(df_f, select = -c(Case_Fatality_Ratio, Incident_Rate, Year))))
plot(clusters)
# Define colors based on outcome variable
outcome_var <- df_f$Case_Fatality_Ratio
outcome_colors <- ifelse(outcome_var > mean(outcome_var), "red", "blue") 
rect.hclust(clusters, k = 5, border = outcome_colors)






```

```{r}
#numeric_cols_i <- sapply(df_i, is.numeric)
df_i$State <- as.factor(df_i$State)
df_i$Month <- as.factor(df_i$Month)
clusters2 <- hclust(dist(subset(df_i, select = -c(Case_Fatality_Ratio, Incident_Rate, Year))))
plot(clusters2)
# Define colors based on outcome variable
outcome_var <- df_i$Incident_Rate
outcome_colors <- ifelse(outcome_var > mean(outcome_var), "red", "blue") 
rect.hclust(clusters2, k = 5, border = outcome_colors)

```

Looking deeper into the Case Fatality Ratio
```{r}
library(plotly)
# Plot the data with plotly
fig <- plot_ly(df_f, x = ~Temp, y = ~Atmospheric.Pressure, z = ~Value,
               color = ~Case_Fatality_Ratio, colors = "Blues",
               type = "scatter3d", mode = "markers")

# Set axis labels
fig <- fig %>% layout(scene = list(xaxis = list(title = "Temperature"),
                                   yaxis = list(title = "Atmospheric Pressure"),
                                   zaxis = list(title = "Value")))

# Show the plot
fig

```

```{r}
library(plotly)
# Plot the data with plotly
fig <- plot_ly(df_i, x = ~Temp, y = ~Atmospheric.Pressure, z = ~Value,
               color = ~Incident_Rate, colors = "Blues",
               type = "scatter3d", mode = "markers")

# Set axis labels
fig <- fig %>% layout(scene = list(xaxis = list(title = "PC 1"),
                                   yaxis = list(title = "PC 2"),
                                   zaxis = list(title = "PC 3")))

# Show the plot
fig

```