---
title: "PCA Full Data"
author: "Sophia Leeman"
date: "2023-04-04"
output: html_document
---

```{r}
library(factoextra)
library(tidyverse)
library(corrplot)
```

```{r}
df_f <- read.csv("TrainTestDatasets/Train_CaseFatality.csv")
df_i <- read.csv("TrainTestDatasets/Train_Incident.csv")

df_f<-subset(df_f, select = -c(Year, Incident_Rate, Case_Fatality_Ratio, Indicator))
df_i<-subset(df_i, select = -c(Year, Case_Fatality_Ratio, Incident_Rate, Indicator))

df_f$State <- as.factor(df_f$State)
df_f$Month <- as.factor(df_f$Month)
df_i$State <- as.factor(df_i$State)
df_i$Month <- as.factor(df_i$Month)

df_f <- df_f %>% rename('Mental_Health' = 'Value')
df_i <- df_i %>% rename('Mental_Health' = 'Value')
```

```{r}
numeric_cols_f <- sapply(df_f, is.numeric)
head(df_f[numeric_cols_f])
pca_f <- prcomp(df_f[numeric_cols_f])
pca_f

numeric_cols_i <- sapply(df_i, is.numeric)
pca_i <- prcomp(df_i[numeric_cols_i])
pca_i
```

```{r}
graph_f <- fviz_eig(pca_f, addlabels = T) 
graph_f
graph_i <- fviz_eig(pca_i, addlabels = T) 
graph_i
```
I would chose to use 3 dimensions by analysis of the location of the elbow in the graph.
```{r}
varPercent_f <- pca_f$sdev^2/sum(pca_f$sdev^2)*100
cumVar_f <- sum(varPercent_f[1:3])
cumVar_f

varPercent_i <- pca_i$sdev^2/sum(pca_i$sdev^2)*100
cumVar_i <- sum(varPercent_i[1:3])
cumVar_i
```
This accounts for 65% of the variance.

```{r}
loadings_f <- pca_f$rotation
loadings_f <- as.data.frame(loadings_f[,1:4])
loadings_f  %>% arrange(desc(.312*abs(PC1)+.176*abs(PC2)+.126*abs(PC3)+.08*abs(PC4)))

loadings_i <- pca_i$rotation
loadings_i <- as.data.frame(loadings_i[,1:4])
loadings_i  %>% arrange(desc(.312*abs(PC1)+.176*abs(PC2)+.126*abs(PC3)+.08*abs(PC4)))

```

```{r}
fviz_pca_ind(pca_f,
             col.ind = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     
             )

fviz_pca_ind(pca_i,
             col.ind = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     
             )
```

Visualize dimensions
```{r, fig.align = "center", fig.height = 4, fig.width = 4 ,out.width = "4in"}
fviz_pca_biplot(pca_f, col.var = "contrib", repel = TRUE) 
fviz_pca_biplot(pca_i, col.var = "contrib", repel = TRUE) 
```

```{r, fig.align = "center", fig.height = 4, fig.width = 4,out.width = "4in"}
fviz_pca_var(pca_f,
             col.var = "contrib", 
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE   
             )
fviz_pca_var(pca_i,
             col.var = "contrib", 
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE   
             )
```

```{r, fig.align = "center", fig.height = 4, fig.width = 4 ,out.width = "4in"}
fviz_pca_var(pca_f, col.var = "contrib", repel = TRUE) 
fviz_pca_var(pca_i, col.var = "contrib", repel = TRUE)
```

The first 3 are significant
```{r}
library(PCAtest)

output <- capture.output({
PCAtest(df_f[numeric_cols_f], 100, 100, 0.05, varcorr=FALSE, counter=FALSE, plot=TRUE)
})
cat(output, file = "significance_PCA_f.txt")

output2 <- capture.output({
PCAtest(df_i[numeric_cols_i], 100, 100, 0.05, varcorr=FALSE, counter=FALSE, plot=TRUE)
})
cat(output2, file = "significance_PCA_i.txt")
```
```{r}
df_f <- read.csv("TrainTestDatasets/Train_CaseFatality.csv")
df_i <- read.csv("TrainTestDatasets/Train_Incident.csv")

df_f <- cbind(df_f, pca_f$x[,1:3])

df_i <- cbind(df_i, pca_i$x[,1:3])

write.csv(df_f, "TrainTestDatasets/Train_CaseFatality_PCA.csv", row.names=FALSE)
write.csv(df_i, "TrainTestDatasets/Train_Incident_PCA.csv", row.names=FALSE)


```

```{r}

# Load required libraries
library(dplyr)
library(magrittr)
library(caret)

tf_f <- read.csv("TrainTestDatasets/Test_CaseFatality.csv")
tf_f <- subset(tf_f, select = -c(Year, Incident_Rate, Case_Fatality_Ratio, Indicator))
tf_f$State <- as.factor(tf_f$State)
tf_f$Month <- as.factor(tf_f$Month)

numeric_cols_tf <- sapply(tf_f, is.numeric)
tf_f <- tf_f[numeric_cols_tf]
pca_mat <- as.matrix(pca_f$rotation)

pca_df <- data.frame(PC1 = numeric(nrow(tf_f)), 
                     PC2 = numeric(nrow(tf_f)),
                    PC3 = numeric(nrow(tf_f)))
colnames(pca_df) <- c("PC1", "PC2", "PC3")
# loop through rows of tf_f and calculate PC scores
for (i in 1:nrow(tf_f)) {
  # loop through columns of pca_mat and calculate contribution to each PC
  for (j in 1:nrow(pca_mat)) {
    pca_df[i, "PC1"] <- pca_df[i, "PC1"] + pca_mat[j, 1] * tf_f[i, j]
    pca_df[i, "PC2"] <- pca_df[i, "PC2"] + pca_mat[j, 2] * tf_f[i, j]
    pca_df[i, "PC3"] <- pca_df[i, "PC3"] + pca_mat[j, 3] * tf_f[i, j]
  }
}

tf_f <- read.csv("TrainTestDatasets/Test_CaseFatality.csv")
tf_f <- cbind(tf_f, pca_df)

tf_i <- read.csv("TrainTestDatasets/Test_Incident.csv")
tf_i <- subset(tf_i, select = -c(Year, Incident_Rate, Case_Fatality_Ratio, Indicator))
tf_i$State <- as.factor(tf_i$State)
tf_i$Month <- as.factor(tf_i$Month)

numeric_cols_ti <- sapply(tf_i, is.numeric)
tf_i <- tf_i[numeric_cols_ti]
pca_mat <- as.matrix(pca_i$rotation)

pca_df <- data.frame(PC1 = numeric(nrow(tf_i)), 
                     PC2 = numeric(nrow(tf_i)),
                     PC3 = numeric(nrow(tf_i)))
colnames(pca_df) <- c("PC1", "PC2", "PC3")
# loop through rows of tf_f and calculate PC scores
for (i in 1:nrow(tf_i)) {
  # loop through columns of pca_mat and calculate contribution to each PC
  for (j in 1:nrow(pca_mat)) {
    pca_df[i, "PC1"] <- pca_df[i, "PC1"] + pca_mat[j, 1] * tf_i[i, j]
    pca_df[i, "PC2"] <- pca_df[i, "PC2"] + pca_mat[j, 2] * tf_i[i, j]
    pca_df[i, "PC3"] <- pca_df[i, "PC3"] + pca_mat[j, 3] * tf_i[i, j]
  }
}

tf_i <- read.csv("TrainTestDatasets/Test_Incident.csv")
tf_i <- cbind(tf_i, pca_df)

write.csv(tf_f, "TrainTestDatasets/Test_CaseFatality_PCA.csv", row.names=FALSE)
write.csv(tf_i, "TrainTestDatasets/Test_IncidentRate_PCA.csv", row.names=FALSE)

```

